### ISSUE TITLE
Can`t build on ubuntu 14.04

### ISSUE THREAD

**Issue by neochapay** [nemomobile/libdsme#4]
make
gcc -o ut_libdsme -pthread $(pkg-config --libs glib-2.0) $(pkg-config --libs check) -L/home/avis/NEMO/libdsme  tests/ut_libdsme.o   -ldsme
tests/ut_libdsme.o: In function `test_send_receive':
/home/avis/NEMO/libdsme/tests/ut_libdsme.c:141: undefined reference to `tcase_fn_start'
/home/avis/NEMO/libdsme/tests/ut_libdsme.c:144: undefined reference to `_ck_assert_msg'
/home/avis/NEMO/libdsme/tests/ut_libdsme.c:156: undefined reference to `_ck_assert_msg'
/home/avis/NEMO/libdsme/tests/ut_libdsme.c:160: undefined reference to `_ck_assert_msg'
/home/avis/NEMO/libdsme/tests/ut_libdsme.c:162: undefined reference to `_ck_assert_msg'
/home/avis/NEMO/libdsme/tests/ut_libdsme.c:165: undefined reference to `_ck_assert_msg'
tests/ut_libdsme.o:/home/avis/NEMO/libdsme/tests/ut_libdsme.c:166: more undefined references to `_ck_assert_msg' follow
tests/ut_libdsme.o: In function `test_message':
/home/avis/NEMO/libdsme/tests/ut_libdsme.c:128: undefined reference to `tcase_fn_start'
/home/avis/NEMO/libdsme/tests/ut_libdsme.c:134: undefined reference to `_ck_assert_msg'
/home/avis/NEMO/libdsme/tests/ut_libdsme.c:135: undefined reference to `_ck_assert_msg'
tests/ut_libdsme.o: In function `libdsme_suite':
/home/avis/NEMO/libdsme/tests/ut_libdsme.c:176: undefined reference to `suite_create'
/home/avis/NEMO/libdsme/tests/ut_libdsme.c:178: undefined reference to `tcase_create'
/home/avis/NEMO/libdsme/tests/ut_libdsme.c:180: undefined reference to `_tcase_add_test'
/home/avis/NEMO/libdsme/tests/ut_libdsme.c:181: undefined reference to `_tcase_add_test'
/home/avis/NEMO/libdsme/tests/ut_libdsme.c:183: undefined reference to `suite_add_tcase'
tests/ut_libdsme.o: In function `main':
/home/avis/NEMO/libdsme/tests/ut_libdsme.c:211: undefined reference to `srunner_create'
/home/avis/NEMO/libdsme/tests/ut_libdsme.c:213: undefined reference to `srunner_set_xml'
/home/avis/NEMO/libdsme/tests/ut_libdsme.c:214: undefined reference to `srunner_run_all'
/home/avis/NEMO/libdsme/tests/ut_libdsme.c:215: undefined reference to `srunner_ntests_failed'
/home/avis/NEMO/libdsme/tests/ut_libdsme.c:216: undefined reference to `srunner_free'
/home/avis/NEMO/libdsme/libdsme.so: undefined reference to `g_slist_find'
/home/avis/NEMO/libdsme/libdsme.so: undefined reference to `g_slist_prepend'
/home/avis/NEMO/libdsme/libdsme.so: undefined reference to `g_slist_delete_link'
collect2: error: ld returned 1 exit status
make[1]: *** [ut_libdsme] Error 1
make: *** [all] Error 2
